package com.example.PrcureflowBackend.assetrequest;

public enum AssetRequestStatus {
	REQUEST_SUBMITTED,
	UNDER_HR_REVIEW,
	SENT_TO_DEALER,
	DEALER_QUOTATION_RECEIVED,
	SENT_FOR_FINAL_APPROVAL,
	FINAL_APPROVED,
	FINAL_REJECTED,
	ORDER_SENT_TO_DEALER,
	DEALER_PROCESSING,
	DELIVERED,
	EMPLOYEE_NOTIFIED,
	CLOSED
}